# devops/dev/docker-compose-dev.yml con auto-deploy locale
version: '3.8'

services:
  ice-pulse-api:
    image: docker.io/aipioppi/ice-pulse-api:dev-latest  # Usa sempre dev-latest
    container_name: ice-pulse-api-dev
    ports:
      - "8080:80"
    environment:
      - ENVIRONMENT=development
      - NODE_ENV=development
    restart: unless-stopped
    
    # Label per Watchtower
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=dev"
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 128M
    
    # Health check
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Watchtower per auto-update DEV
  watchtower-dev:
    image: containrrr/watchtower
    container_name: watchtower-dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true           # Rimuovi immagini vecchie
      - WATCHTOWER_POLL_INTERVAL=180      # Check ogni 3 minuti (per dev)
      - WATCHTOWER_LABEL_ENABLE=true      # Solo container con label
      - WATCHTOWER_SCOPE=dev              # Solo scope dev
      - WATCHTOWER_NOTIFICATIONS=slack    # Opzionale: notifiche
      - WATCHTOWER_DEBUG=true             # Debug per dev
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.scope=dev"