version: '3.8'
services:
  ice-pulse-ota-dev:
    image: aipioppi/ice-pulse-firmware-ota:0.0.5
    container_name: ice-pulse-ota-dev
    ports:
      - "8092:5000"
    environment:
      - ENVIRONMENT=development
      - FIRMWARE_VERSION=0.0.5
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
