# jenkins-sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-sa
  namespace: argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-sa-binding
subjects:
- kind: ServiceAccount
  name: jenkins-sa
  namespace: argocd
roleRef:
  kind: ClusterRole
  name: cluster-admin      # o un Role con permessi su ApplicationSet
  apiGroup: rbac.authorization.k8s.io
