global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'hub-central'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8000']  # su Windows usa host.docker.internal

  - job_name: 'kafka'
    metrics_path: /metrics  # se esponi metriche Kafka client
    static_configs:
      - targets: ['host.docker.internal:8000']

  # (opzionale) scrape di Prometheus stesso
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
