# devops/prod/ice-pulse-api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ice-pulse-api
  namespace: prod
  labels:
    app: ice-pulse-api
    environment: production
spec:
  replicas: 3  # Più replicas per alta disponibilità in prod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: ice-pulse-api
  template:
    metadata:
      labels:
        app: ice-pulse-api
        environment: production
        test-sync: "true"  # label di verifica
    spec:
      containers:
        - name: ice-pulse-api
          image: nginx:stable-alpine  # Sarà aggiornata da Jenkins
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "200m"     # Risorse maggiori per produzione
              memory: "512Mi"
            limits:
              cpu: "1000m"    # Limite più alto per prod
              memory: "1Gi"
          env:
            - name: ENVIRONMENT
              value: "production"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          # Security context per produzione
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL