# helm/hub-central/Chart.yaml

apiVersion: v2              # Helm v3 usa apiVersion:v2
name: hub-central            # Nome del chart, corrisponde al package Python
description: >-
  Helm chart per il deploy di Hub Central (FastAPI), con configurazioni
  parametriche per DB, Kafka e agenti.
type: application            # Chart per un’applicazione (non libreria)
version: 0.1.1               # Versione del chart (semver chart vs appVersion)
appVersion: "latest"         # Tag dell’immagine Docker da usare
keywords:
  - fastapi
  - hub-central
  - kafka
  - postgres
home: https://github.com/GianlucaCelante/hub-central
maintainers:
  - name: Gianluca Celante
    email: osteriaaipioppiai@gmail.com
