# helm/hub-central/values-dev.yaml
# → ambiente “staging / test”
# (dati da riempire man mano, qui lasciati vuoti o con placeholder)

replicaCount: 2

image:
  repository: "<DEV_REGISTRY>/hub-central"
  tag: "<TAG>"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: false
  className: nginx
  hosts:
    - host: ""
      paths: ["/"]

resources:
  requests:
    cpu: ""
    memory: ""
  limits:
    cpu: ""
    memory: ""

config:
  enable: false                 # useremo Secret in staging
  env: |
    DB_USER=${DB_USER}
    DB_PASSWORD=${DB_PASSWORD}
    DB_HOST=${DB_HOST}
    DB_PORT=${DB_PORT}
    DB_NAME=${DB_NAME}
    KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
    AGENTS_PACKAGE=${AGENTS_PACKAGE}
    AGENTS_LIST=${AGENTS_LIST}
    KAFKA_TOPIC=${KAFKA_TOPIC}
    DEBUG=${DEBUG}

env:
  DB_USER: ""
  DB_PASSWORD: ""
  DB_HOST: ""
  DB_PORT: ""
  DB_NAME: ""
  AGENTS_PACKAGE: "hub_central.agents"
  AGENTS_LIST: '["dummy_agent"]'
  KAFKA_TOPIC: ""
  DEBUG: "false"
