# helm/hub-central/values.yaml
# → ambiente “locale / testing rapido”

replicaCount: 1

image:
  repository: hub-central      # immagine locale
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: false               # non serve Ingress in locale
  className: nginx
  hosts:
    - host: ""
      paths: ["/"]

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

config:
  enable: true                 # monta .env
  env: |
    DB_USER=${DB_USER}
    DB_PASSWORD=${DB_PASSWORD}
    DB_HOST=${DB_HOST}
    DB_PORT=${DB_PORT}
    DB_NAME=${DB_NAME}
    KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
    AGENTS_PACKAGE=${AGENTS_PACKAGE}
    AGENTS_LIST=${AGENTS_LIST}
    KAFKA_TOPIC=${KAFKA_TOPIC}
    DEBUG=${DEBUG}

env:
  DB_USER: "postgres"
  DB_PASSWORD: "mysecret"
  DB_HOST: "localhost"
  DB_PORT: "5432"
  DB_NAME: "hub-central-db"
  AGENTS_PACKAGE: "hub_central.agents"
  AGENTS_LIST: '["dummy_agent"]'
  KAFKA_TOPIC: "inventory.events"
  DEBUG: "true"
