# devops/argocd/applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ice-pulse-all-envs
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/tuo-org/ice-pulse-infra.git
        revision: master
        directories:
          - path: devops/dev
          - path: devops/staging
          - path: devops/prod
  template:
    metadata:
      name: "ice-pulse-{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/tuo-org/ice-pulse-infra.git
        targetRevision: master
        path: "devops/{{path.basename}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
