# ice-pulse-infra/devops/argocd/projects.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ice-pulse-infra   # nome del Project
  namespace: argocd  # il namespace di ArgoCD
spec:
  description: >-
    Progetto per tutte le applicazioni Ice-Pulse (dev, staging, prod)
  sourceRepos:
    - 'https://github.com/GianlucaCelante/ice-pulse-infra.git'   # repo da cui può sincronizzare
  destinations:
    - namespace: dev
      server: 'https://kubernetes.default.svc'
    - namespace: staging
      server: 'https://kubernetes.default.svc'
    - namespace: prod
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:   # se servono CRD di cluster scoped
    - group: '*'
      kind: '*'
  syncWindows: []             # qui puoi bloccare deploy in certe fasce orarie
  roles:
    - name: developers
      policies:
        - p, proj:ice-pulse:developers, applications, get, ice-pulse-*, allow
        - p, proj:ice-pulse:developers, applications, sync, ice-pulse-*-dev, allow
      groups:
        - dev-team       # corrisponde a un gruppo RBAC esterno
